language: objective-c
os: osx
osx_image: xcode7.3
env:
  matrix:
    - TEST_TYPE=iOS
    - TEST_TYPE=CocoaPods
    - TEST_TYPE=Carthage
install:
- |
  if [ "$TEST_TYPE" = "iOS" ]; then
    gem install xcpretty -N --no-ri --no-rdoc
    gem update cocoapods
  elif [ "$TEST_TYPE" = Carthage ]; then    
    brew install carthage || brew upgrade carthage
  fi
script:
- |
  if [ "$TEST_TYPE" = "iOS" ]; then
    set -o pipefail
    xcodebuild build -project FXNotifications.xcodeproj -scheme FXNotifications-iOS -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 4s" | xcpretty -c
  elif [ "$TEST_TYPE" = CocoaPods ]; then
    pod lib lint FXNotifications.podspec.json
    pod lib lint --use-libraries FXNotifications.podspec.json
  elif [ "$TEST_TYPE" = Carthage ]; then
    carthage build --no-skip-current
  fi
